wandb: Currently logged in as: nreints. Use `wandb login --relogin` to force relogin
wandb: wandb version 0.15.1 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.0
wandb: Run data is saved locally in /gpfs/home2/nreints/MScThesis/code/wandb/run-20230503_122819-fn08pzw9
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run expert-hill-86
wandb: ‚≠êÔ∏è View project at https://wandb.ai/nreints/ThesisF
wandb: üöÄ View run at https://wandb.ai/nreints/ThesisF/runs/fn08pzw9
wandb: ERROR Dropped streaming file chunk (see wandb/debug-internal.log)
wandb: ERROR Dropped streaming file chunk (see wandb/debug-internal.log)
wandb: ERROR Dropped streaming file chunk (see wandb/debug-internal.log)
wandb: ERROR Dropped streaming file chunk (see wandb/debug-internal.log)
wandb: ERROR Dropped streaming file chunk (see wandb/debug-internal.log)
wandb: ERROR Dropped streaming file chunk (see wandb/debug-internal.log)
wandb: ERROR Dropped streaming file chunk (see wandb/debug-internal.log)
wandb: ERROR Dropped streaming file chunk (see wandb/debug-internal.log)
wandb: ERROR Dropped streaming file chunk (see wandb/debug-internal.log)
wandb: ERROR Dropped streaming file chunk (see wandb/debug-internal.log)
wandb: ERROR Dropped streaming file chunk (see wandb/debug-internal.log)
wandb: ERROR Dropped streaming file chunk (see wandb/debug-internal.log)
wandb: ERROR Dropped streaming file chunk (see wandb/debug-internal.log)
wandb: ERROR Dropped streaming file chunk (see wandb/debug-internal.log)
wandb: ERROR Error while calling W&B API: run nreints/ThesisF/fn08pzw9 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run nreints/ThesisF/fn08pzw9 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run nreints/ThesisF/fn08pzw9 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run nreints/ThesisF/fn08pzw9 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run nreints/ThesisF/fn08pzw9 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run nreints/ThesisF/fn08pzw9 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run nreints/ThesisF/fn08pzw9 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run nreints/ThesisF/fn08pzw9 was previously created and deleted; try a new run name (<Response [409]>)
Thread SenderThread:
Traceback (most recent call last):
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/apis/normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 1664, in upsert_run
    response = self.gql(
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 215, in gql
    ret = self._retry_gql(
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 243, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 93, in _run
    self._debounce()
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/internal/internal.py", line 335, in _debounce
    self._sm.debounce()
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 512, in debounce
    self._maybe_update_config(always=final)
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 489, in _maybe_update_config
    self._debounce_config()
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 518, in _debounce_config
    self._api.upsert_run(
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/apis/normalize.py", line 27, in wrapper
    raise CommError(err.response, err)
wandb.errors.CommError: <Response [409]>
wandb: ERROR Internal wandb error: file data was not synced
with replace ['data_t(5,20)_r(0,0)_semi_pNone_gNone', 'data_t(5,20)_r(0,0)_full_pNone_gNone', 'data_t(5,20)_r(0,0)_tennis_pNone_gNone', 'data_t(5,20)_r(0,0)_none_pNone_gNone', 'data_t(0,0)_r(5,20)_semi_pNone_gNone', 'data_t(0,0)_r(5,20)_full_pNone_gNone', 'data_t(0,0)_r(5,20)_tennis_pNone_gNone', 'data_t(0,0)_r(5,20)_none_pNone_gNone', 'data_t(5,20)_r(5,20)_semi_pNone_gNone', 'data_t(5,20)_r(5,20)_full_pNone_gNone', 'data_t(5,20)_r(5,20)_tennis_pNone_gNone', 'data_t(5,20)_r(5,20)_none_pNone_gNone', 'data_tennis_pNone_gNone_tennisEffect']
Training on dataset: data_t(5,20)_r(5,20)_combi_pNone_gNone
test directories ['"data_t(5,20)_r(0,0)_semi_pNone_gNone"', '"data_t(5,20)_r(0,0)_full_pNone_gNone"', '"data_t(5,20)_r(0,0)_tennis_pNone_gNone"', '"data_t(5,20)_r(0,0)_none_pNone_gNone"', '"data_t(0,0)_r(5,20)_semi_pNone_gNone"', '"data_t(0,0)_r(5,20)_full_pNone_gNone"', '"data_t(0,0)_r(5,20)_tennis_pNone_gNone"', '"data_t(0,0)_r(5,20)_none_pNone_gNone"', '"data_t(5,20)_r(5,20)_semi_pNone_gNone"', '"data_t(5,20)_r(5,20)_full_pNone_gNone"', '"data_t(5,20)_r(5,20)_tennis_pNone_gNone"', '"data_t(5,20)_r(5,20)_none_pNone_gNone"', '"data_tennis_pNone_gNone_tennisEffect"']
with join ['" d a t a _ t ( 5 , 2 0 ) _ r ( 0 , 0 ) _ s e m i _ p N o n e _ g N o n e "', '" d a t a _ t ( 5 , 2 0 ) _ r ( 0 , 0 ) _ f u l l _ p N o n e _ g N o n e "', '" d a t a _ t ( 5 , 2 0 ) _ r ( 0 , 0 ) _ t e n n i s _ p N o n e _ g N o n e "', '" d a t a _ t ( 5 , 2 0 ) _ r ( 0 , 0 ) _ n o n e _ p N o n e _ g N o n e "', '" d a t a _ t ( 0 , 0 ) _ r ( 5 , 2 0 ) _ s e m i _ p N o n e _ g N o n e "', '" d a t a _ t ( 0 , 0 ) _ r ( 5 , 2 0 ) _ f u l l _ p N o n e _ g N o n e "', '" d a t a _ t ( 0 , 0 ) _ r ( 5 , 2 0 ) _ t e n n i s _ p N o n e _ g N o n e "', '" d a t a _ t ( 0 , 0 ) _ r ( 5 , 2 0 ) _ n o n e _ p N o n e _ g N o n e "', '" d a t a _ t ( 5 , 2 0 ) _ r ( 5 , 2 0 ) _ s e m i _ p N o n e _ g N o n e "', '" d a t a _ t ( 5 , 2 0 ) _ r ( 5 , 2 0 ) _ f u l l _ p N o n e _ g N o n e "', '" d a t a _ t ( 5 , 2 0 ) _ r ( 5 , 2 0 ) _ t e n n i s _ p N o n e _ g N o n e "', '" d a t a _ t ( 5 , 2 0 ) _ r ( 5 , 2 0 ) _ n o n e _ p N o n e _ g N o n e "', '" d a t a _ t e n n i s _ p N o n e _ g N o n e _ t e n n i s E f f e c t "']
Testing on 14 datasets: ['data_tennis_pNone_gNone_tennisEffect', 'data_t(5,20)_r(5,20)_none_pNone_gNone', 'data_t(5,20)_r(0,0)_full_pNone_gNone', 'data_t(0,0)_r(5,20)_semi_pNone_gNone', 'data_t(5,20)_r(5,20)_full_pNone_gNone', 'data_t(5,20)_r(0,0)_tennis_pNone_gNone', 'data_t(0,0)_r(5,20)_tennis_pNone_gNone', 'data_t(5,20)_r(5,20)_combi_pNone_gNone', 'data_t(5,20)_r(5,20)_tennis_pNone_gNone', 'data_t(0,0)_r(5,20)_none_pNone_gNone', 'data_t(5,20)_r(0,0)_semi_pNone_gNone', 'data_t(5,20)_r(5,20)_semi_pNone_gNone', 'data_t(5,20)_r(0,0)_none_pNone_gNone', 'data_t(0,0)_r(5,20)_full_pNone_gNone']
----- ITERATION 1/2 ------
Total number of simulations in train dir:  2400
Checked number of simulations in each data directory.
Number of train simulations:  1920
Number of test simulations:  480
The dataloader for data/data_t(5,20)_r(5,20)_combi_pNone_gNone took 115.95716500282288 seconds.
-- Finished Train Dataloader --
The dataloader for data/data_tennis_pNone_gNone_tennisEffect took 29.366472959518433 seconds.
The dataloader for data/data_t(5,20)_r(5,20)_none_pNone_gNone took 29.91619634628296 seconds.
The dataloader for data/data_t(5,20)_r(0,0)_full_pNone_gNone took 30.330430269241333 seconds.
The dataloader for data/data_t(0,0)_r(5,20)_semi_pNone_gNone took 29.31499195098877 seconds.
The dataloader for data/data_t(5,20)_r(5,20)_full_pNone_gNone took 29.229648113250732 seconds.
The dataloader for data/data_t(5,20)_r(0,0)_tennis_pNone_gNone took 29.435202598571777 seconds.
The dataloader for data/data_t(0,0)_r(5,20)_tennis_pNone_gNone took 29.295223474502563 seconds.
The dataloader for data/data_t(5,20)_r(5,20)_combi_pNone_gNone took 29.009600400924683 seconds.
The dataloader for data/data_t(5,20)_r(5,20)_tennis_pNone_gNone took 29.311272621154785 seconds.
The dataloader for data/data_t(0,0)_r(5,20)_none_pNone_gNone took 29.63283061981201 seconds.
The dataloader for data/data_t(5,20)_r(0,0)_semi_pNone_gNone took 29.51396417617798 seconds.
The dataloader for data/data_t(5,20)_r(5,20)_semi_pNone_gNone took 29.74069094657898 seconds.
The dataloader for data/data_t(5,20)_r(0,0)_none_pNone_gNone took 29.470520734786987 seconds.
The dataloader for data/data_t(0,0)_r(5,20)_full_pNone_gNone took 29.44769525527954 seconds.
-- Finished Test Dataloader(s) --
GRU(
  (rnn): GRU(8, 96, batch_first=True)
  (fc): Linear(in_features=96, out_features=8, bias=True)
)
Datatype: dual_quat
-- Started Training --
Epoch 0/9
	 Logging train Loss: 13.4796695709 [MSELoss(): t(5,20)_r(5,20)_combi_pNone_gNone]
	 Logging test loss: 9.2160196304 [MSELoss(): tennis_pNone_gNone_tennisEffect]
	 Logging test loss: 0.1885911524 [MSELoss(): t(5,20)_r(5,20)_none_pNone_gNone]
	 Logging test loss: 0.088319771 [MSELoss(): t(5,20)_r(0,0)_full_pNone_gNone]
	 Logging test loss: 1.4071739912 [MSELoss(): t(0,0)_r(5,20)_semi_pNone_gNone]
	 Logging test loss: 0.1761036366 [MSELoss(): t(5,20)_r(5,20)_full_pNone_gNone]
	 Logging test loss: 0.3964206278 [MSELoss(): t(5,20)_r(0,0)_tennis_pNone_gNone]
	 Logging test loss: 1.5048028231 [MSELoss(): t(0,0)_r(5,20)_tennis_pNone_gNone]
	 Logging test loss: 0.6736029983 [MSELoss(): t(5,20)_r(5,20)_combi_pNone_gNone]
	 Logging test loss: 0.9928069115 [MSELoss(): t(5,20)_r(5,20)_tennis_pNone_gNone]
	 Logging test loss: 0.0506182015 [MSELoss(): t(0,0)_r(5,20)_none_pNone_gNone]
	 Logging test loss: 0.379273504 [MSELoss(): t(5,20)_r(0,0)_semi_pNone_gNone]
	 Logging test loss: 0.8662903309 [MSELoss(): t(5,20)_r(5,20)_semi_pNone_gNone]
Traceback (most recent call last):
  File "/gpfs/home2/nreints/MScThesis/code/utils.py", line 301, in model_pipeline
    train_fn(
  File "/gpfs/home2/nreints/MScThesis/code/gru.py", line 173, in train_model
    convert_loss = eval_model(
  File "/gpfs/home2/nreints/MScThesis/code/gru.py", line 210, in eval_model
    _, _, preds = model(
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1215, in _call_impl
    hook_result = hook(self, input, result)
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/wandb_torch.py", line 110, in <lambda>
    lambda mod, inp, outp: parameter_log_hook(
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/wandb_torch.py", line 105, in parameter_log_hook
    self.log_tensor_stats(data.cpu(), "parameters/" + prefix + name)
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/wandb_torch.py", line 256, in log_tensor_stats
    wandb.run._log(
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1496, in _log
    self._partial_history_callback(data, step, commit)
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1366, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 585, in publish_partial_history
    self._publish_partial_history(partial_history)
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 89, in _publish_partial_history
    self._publish(rec)
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/home2/nreints/MScThesis/code/gru.py", line 283, in <module>
    model = model_pipeline(
  File "/gpfs/home2/nreints/MScThesis/code/utils.py", line 274, in model_pipeline
    with wandb.init(
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2999, in __exit__
    self._finish(exit_code)
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1852, in _finish
    with telemetry.context(run=self) as tel:
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 691, in _telemetry_callback
    self._telemetry_flush()
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 702, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 101, in _publish_telemetry
    self._publish(rec)
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nreints/.conda/envs/thesis/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
wandb: While tearing down the service manager. The following error has occurred: [Errno 32] Broken pipe
srun: error: gcn30: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=2683577.0

JOB STATISTICS
==============
Job ID: 2683577
Array Job ID: 2683569_5
Cluster: snellius
User/Group: nreints/nreints
State: FAILED (exit code 1)
Nodes: 1
Cores per node: 18
CPU Utilized: 00:41:46
CPU Efficiency: 19.75% of 03:31:30 core-walltime
Job Wall-clock time: 00:11:45
Memory Utilized: 31.04 GB
Memory Efficiency: 0.00% of 0.00 MB
